# Screen Size
SCREEN_SIZE = (640, 480)

# Brick Dimensions
BRICK_WIDTH = 60
BRICK_HEIGHT = 15
BRICKS_ROW = 7
BRICKS_COLUMN = 8

# Paddle Dimensions
PADDLE_WIDTH = 70
PADDLE_HEIGHT = 12
PADDLE_SPEED_LEFT = 15
PADDLE_SPEED_RIGHT = 15

# Ball Dimensions
BALL_DIAMETER = 16
BALL_RADIUS = int(BALL_DIAMETER / 2)

# Positions
MAX_PADDLE_X = SCREEN_SIZE[0] - PADDLE_WIDTH
MAX_BALL_X = SCREEN_SIZE[0] - BALL_DIAMETER
MAX_BALL_Y = SCREEN_SIZE[1] - BALL_DIAMETER

# Paddle Y coordinate
PADDLE_Y = SCREEN_SIZE[1] - PADDLE_HEIGHT - 10

# Color
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
YELLOW = (200, 200, 0)
RED = (220, 0, 0)
BRICK_COLOR = RED
GREEN = (0, 128, 0)

# Game State
STATE_BALL_IN_PADDLE = 0
STATE_PLAYING = 1
STATE_WON = 2
STATE_GAME_OVER = 3

MAX_LIFE = 3
MAX_SCORE_PER_BRICK = 10
